// react-version/src/App.tsx
import React from "react"

import * as data from "./items"

import "./App.css"

console.log("data", data)

function App() {
	const [filteredItems, setFilteredItems] = React.useState(data.items)

	React.useEffect(() => {
		setFilteredItems(data.items)
	}, [data])

	const handleFilter = (event: React.ChangeEvent<HTMLInputElement>) => {
		let _filteredItems = data.items.filter((item) =>
			item.title
				.toLocaleLowerCase()
				.includes(event.target.value.toLocaleLowerCase()),
		)
		setFilteredItems(_filteredItems)
	}

	return (
		<div className="app">
			<div className="app-wrapper">
				<div className="search-bar">
					<h2>Search items</h2>
					<input
						id="search"
						type="search"
						className="search"
						placeholder="start typing"
						onChange={handleFilter}
					/>
				</div>
				<div className="items-wrapper" id="items-wrapper">
					{filteredItems.map((item) => (
						<div className="item-card" key={item.code}>
							<h2 className="item-card__code">{item.code}</h2>
							<div className="item-card__icon-circle">
								<img src={item.image} alt="banana" />
							</div>
							<p className="item-card__title">{item.title}</p>
						</div>
					))}
				</div>
			</div>
		</div>
	)
}

export default App

// vue-version/src/App.vue
<template>
	<div class="app">
		<div class="app-wrapper">
			<div class="search-bar">
				<h2>Search items</h2>
				<input
					id="search"
					v-model="searchPayload"
					type="search"
					class="search"
					placeholder="start typing"
				/>
			</div>
			<div class="items-wrapper" id="items-wrapper">
				<div class="item-card" v-for="item in filteredItems" :key="item.code">
					<h2 class="item-card__code">{{ item.code }}</h2>
					<div class="item-card__icon-circle">
						<img :src="item.image" alt="banana" />
					</div>
					<p class="item-card__title">{{ item.title }}</p>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
import * as data from "./items"
export default {
	name: "App",
	components: {},
	data: function () {
		return {
			filteredItems: [],
			searchPayload: "",
		}
	},
	watch: {
		searchPayload: function () {
			this.filteredItems = data.items.filter((item) =>
				item.title.toLowerCase().includes(this.searchPayload.toLowerCase()),
			)
		},
	},
	created: function () {
		this.filteredItems = data.items
	},
}
</script>

<style>
:root {
	font-size: 8px;
}
@import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap");
body {
	background-color: #ffffff;
}

h1 {
	font-family: "Montserrat", sans-serif;
	font-size: 3rem;
	font-weight: 500;
	letter-spacing: 2%;
	line-height: 30px;
	color: #464141;
}

h2 {
	font-family: "Montserrat", sans-serif;
	font-size: 2.5rem;
	font-weight: 500;
	letter-spacing: 2%;
	line-height: 24px;
	color: #464141;
}

p {
	font-family: "Montserrat", sans-serif;
	font-size: 2rem;
	font-weight: weight(regular);
	letter-spacing: 2%;
	line-height: 20px;
	color: #a2a4aa;
}
.app {
	margin: auto;
	width: 100%;
	max-width: 1048px;
}
.app-warpper {
	margin: auto;
}

.search-bar {
	text-align: center;
	margin-top: 4rem;
}
.search-bar input {
	padding: 2rem;
	min-width: 40rem;
}

.items-wrapper {
	margin-top: 40px;

	display: flex;
	justify-content: flex-start;
	flex-wrap: wrap;
}

/* item card */
.item-card {
	min-width: 160px;
	min-height: 180px;
	background-color: #f6f6f6;
	border-radius: 7px;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	margin: 0 10px 10px 0;
}

.item-card__icon-circle {
	background-color: #fffcfc;
	width: 85px;
	height: 85px;
	border-radius: 50%;
	margin: 0 auto 0 auto;
	display: flex;
	justify-content: center;
	align-items: center;
}

.item-card__icon-circle img {
	max-width: 60px;
	max-height: 60px;
	object-fit: contain;
}

.item-card__variety {
	color: #464141;
	text-align: center;
	margin: 15px auto 0 auto;
	text-transform: lowercase;
	text-transform: capitalize;
}

.item-card__title {
	font-weight: 500;
	color: #464141;
	margin: 15px auto 15px auto;
	text-transform: lowercase;
	text-transform: capitalize;
}

.item-card__code {
	color: #36b16c;
	margin: 15px auto 0 auto;
}
</style>
